name: Elixir CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.11.4' # Define the elixir version [required]
        otp-version: '23.1' # Define the OTP version [required]
      env:
        ImageOS: ubuntu20
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install postgres
      run: |
        sudo apt-get update
        sudo apt-get install postgresql
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
